"use strict";
exports.__esModule = true;
var RESOLUTION_KEY;
(function (RESOLUTION_KEY) {
    RESOLUTION_KEY[RESOLUTION_KEY["SUCCESS"] = 0] = "SUCCESS";
    RESOLUTION_KEY[RESOLUTION_KEY["TIMEOUT_ERROR"] = 1] = "TIMEOUT_ERROR";
    RESOLUTION_KEY[RESOLUTION_KEY["GENERIC_ERROR"] = 2] = "GENERIC_ERROR";
})(RESOLUTION_KEY = exports.RESOLUTION_KEY || (exports.RESOLUTION_KEY = {}));
