"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var HASHCASH_WORKER_RESOLUTION_KEY;
(function (HASHCASH_WORKER_RESOLUTION_KEY) {
    HASHCASH_WORKER_RESOLUTION_KEY[HASHCASH_WORKER_RESOLUTION_KEY["SUCCESS"] = 0] = "SUCCESS";
    HASHCASH_WORKER_RESOLUTION_KEY[HASHCASH_WORKER_RESOLUTION_KEY["TIMEOUT_ERROR"] = 1] = "TIMEOUT_ERROR";
    HASHCASH_WORKER_RESOLUTION_KEY[HASHCASH_WORKER_RESOLUTION_KEY["GENERIC_ERROR"] = 2] = "GENERIC_ERROR";
})(HASHCASH_WORKER_RESOLUTION_KEY = exports.HASHCASH_WORKER_RESOLUTION_KEY || (exports.HASHCASH_WORKER_RESOLUTION_KEY = {}));
//# sourceMappingURL=HashcashWorker.js.map